### ISSUE TITLE
Save command outputs

### ISSUE THREAD

**Issue by GiselleSerate** [GiselleSerate/pure19prototype#27]
EDIT: make sure you count configs first, #31 
Record your demos!
- [x] CentOS VM
- [x] Ubuntu VM

**Comment by jwsbrennan** [comment]
when you say "Record your demos" do you mean like screen record? Or just save the log files?

**Comment by GiselleSerate** [comment]
Just save the log files, no need for screen recording.

**Comment by jwsbrennan** [comment]
logs are in the site visit folder on the google drive now
