### ISSUE TITLE
Count config files on both systems

### ISSUE THREAD

**Issue by jwsbrennan** [GiselleSerate/pure19prototype#31]

**Comment by jwsbrennan** [comment]
A doc which records these numbers is now on the google drive, under the research folder. It's called Filesystem Analysis Results.

**Comment by GiselleSerate** [comment]
Wait lol you can totally leave those prints in the codebase as logs to stdout, I just forgot to put in those logging statements in earlier

**Comment by jwsbrennan** [comment]
I thought it would be easier to read in table form, I'm leaving the lists of actual file names in log files

**Comment by GiselleSerate** [comment]
This is true, but counts are helpful for the stdout logs--that's the amount of detail that I've left in them currently (it's just that we currently aren't printing how many config files there are total). It's helpful for people who are going to want to run this on systems besides our two.

**Comment by GiselleSerate** [comment]
As for where to put this, just put the commit for this on filesystem and we can merge it into the demo branch. 
Is this ugly? Yes. But it'll work.

**Comment by jwsbrennan** [comment]
it should be committed to filesystem now, it both prints the config counts to stdout and to the log file.

**Comment by GiselleSerate** [comment]
Merged!
